# Generated by Django 5.2.4 on 2025-07-23 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_energy_level_alter_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyphoto',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
