# Generated by Django 5.2.4 on 2025-07-23 20:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_dailyphoto_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyphoto',
            unique_together={('user', 'date')},
        ),
    ]
