# Generated by Django 5.2.4 on 2025-08-07 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='code',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
